[package]
name = "gtk4-rs-examples"
version = "0.1.0"
edition = "2021"

[dependencies]
adw = { version = "0.6.0", package = "libadwaita", features = ["v1_5"] }
gtk = { version = "0.8.1", package = "gtk4", features = ["v4_14"] }
